***Zadanie 1***

In [1]:
import numpy as np
A = np.matrix('1 1; 1 1.0001')
b1 = np.matrix('2; 2.0001')
b2 = np.matrix('2;2')
x1 = np.linalg.inv(A)@b1
x2 = np.linalg.inv(A)@b2

In [2]:
print(x1)
print(x2)
print(np.linalg.cond(A))

[[1.]
 [1.]]
[[2.]
 [0.]]
40002.000074915224


Widzimy, że przy zmianie wartości b o 10<sup>-4</sup>, wartość x zmienia się o 1, zatem widzimy, że współczynnik uwarunkowania powinien być duży i faktycznie wynosi on ponad 40000

***Zadanie 2***

In [12]:
import scipy as sp

A = sp.linalg.hilbert(8)
column = np.linalg.cond(A,np.inf)
print(column)
row = np.linalg.cond(A,1)
print(row)
spectral = np.linalg.cond(A,2)
print(spectral)

33872789109.75766
33872789110.107353
15257575566.627958


In [74]:
import math
n = 20
t = np.linspace(0,1,20)
t.shape = (n,1)

b = np.array([math.cos(4*x) for x in t])
b.shape = (n,1)

t_ = np.linspace(0,1,20)
A = np.vander(t_,increasing = True)

#Z użyciem funkcji solve
x = np.linalg.solve(A,b)
print(x)

#Z użyciem QR
q,r= np.linalg.qr(A)
b_ = np.transpose(q)@b
x2 = sp.linalg.solve_triangular(r,b_)
print(x2)

#Z użyciem lstsq

x3 = np.linalg.lstsq(A,b,rcond = None)[0]
print(x3)

#TODO czasy i analiza

[[ 1.00000000e+00]
 [ 3.32764927e-11]
 [-8.00000000e+00]
 [ 6.35818437e-08]
 [ 1.06666656e+01]
 [ 1.19699204e-05]
 [-5.68898363e+00]
 [ 5.53922234e-04]
 [ 1.62293934e+00]
 [ 8.41840595e-03]
 [-3.11464449e-01]
 [ 4.71900888e-02]
 [-4.25883553e-02]
 [ 9.95878711e-02]
 [-1.01598838e-01]
 [ 7.36115670e-02]
 [-3.99387587e-02]
 [ 1.50687889e-02]
 [-3.49070550e-03]
 [ 3.73507626e-04]]
[[ 1.00000000e+00]
 [-3.68180914e-11]
 [-8.00000000e+00]
 [-6.68040308e-08]
 [ 1.06666678e+01]
 [-1.18047669e-05]
 [-5.68879853e+00]
 [-5.10732658e-04]
 [ 1.62758794e+00]
 [-7.26294062e-03]
 [-2.70154238e-01]
 [-3.82348552e-02]
 [ 9.60780538e-02]
 [-7.61559375e-02]
 [ 7.02589345e-02]
 [-5.34097741e-02]
 [ 2.86281041e-02]
 [-1.04196293e-02]
 [ 2.33851891e-03]
 [-2.44422212e-04]]
[[ 1.00000000e+00]
 [ 1.32997475e-11]
 [-8.00000000e+00]
 [ 2.27399505e-08]
 [ 1.06666663e+01]
 [ 3.63061300e-06]
 [-5.68891467e+00]
 [ 1.32078403e-04]
 [ 1.62489928e+00]
 [ 1.38430832e-03]
 [-2.91765386e-01]
 [ 3.94194537e-03]
 [ 3.18156

***Zadanie 4***

In [88]:
def Matrix(theta=0):
    A = np.ones(500)
    A = np.diag(A)
    B = np.random.rand(500,500)*2-1
    C = np.tril(B,-1)
    A = A+C+np.transpose(C)
    return A


print (Matrix())

[[ 1.          0.70007824 -0.37739748 ... -0.16908432 -0.55607119
  -0.70277455]
 [ 0.70007824  1.          0.19848575 ... -0.13233122  0.45733898
  -0.63725528]
 [-0.37739748  0.19848575  1.         ... -0.93434764 -0.62433503
  -0.88062184]
 ...
 [-0.16908432 -0.13233122 -0.93434764 ...  1.         -0.62754043
  -0.56338002]
 [-0.55607119  0.45733898 -0.62433503 ... -0.62754043  1.
   0.90776588]
 [-0.70277455 -0.63725528 -0.88062184 ... -0.56338002  0.90776588
   1.        ]]
